### ISSUE TITLE
Issues installing the role - .galaxy_install_info not found

### ISSUE THREAD

**Issue by cmarquezrusso** [debops/ansible-php#44]
Issues when installing the role

```
$ ansible-galaxy install --force debops.php  -vvv
Using /Users/cristian04/sec/projects/provisioning-iam-ansible/ansible.cfg as config file
Opened /Users/cristian04/.ansible_galaxy
Installing role debops.php
Opened /Users/cristian04/.ansible_galaxy
- downloading role 'php', owned by debops
https://galaxy.ansible.com/api/v1/roles/?owner__username=debops&name=php
https://galaxy.ansible.com/api/v1/roles/29675/versions/?page_size=50
- downloading role from https://github.com/debops/debops/archive/v0.8.1.tar.gz
- extracting debops.php to /Users/cristian04/sec/projects/provisioning-iam-ansible/galaxy/debops.php
ERROR! Unexpected Exception: [Errno 2] No such file or directory: u'/Users/cristian04/sec/projects/provisioning-iam-ansible/galaxy/debops.php/meta/.galaxy_install_info'
the full traceback was:

Traceback (most recent call last):
  File "/Users/cristian04/sec/projects/provisioning-iam-ansible/bin/ansible-galaxy", line 103, in <module>
    exit_code = cli.run()
  File "/Users/cristian04/sec/projects/provisioning-iam-ansible/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 133, in run
    self.execute()
  File "/Users/cristian04/sec/projects/provisioning-iam-ansible/lib/python2.7/site-packages/ansible/cli/__init__.py", line 145, in execute
    fn()
  File "/Users/cristian04/sec/projects/provisioning-iam-ansible/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 396, in execute_install
    installed = role.install()
  File "/Users/cristian04/sec/projects/provisioning-iam-ansible/lib/python2.7/site-packages/ansible/galaxy/role.py", line 298, in install
    self._write_galaxy_install_info()
  File "/Users/cristian04/sec/projects/provisioning-iam-ansible/lib/python2.7/site-packages/ansible/galaxy/role.py", line 140, in _write_galaxy_install_info
    with open(info_path, 'w+') as f:
IOError: [Errno 2] No such file or directory: u'/Users/cristian04/sec/projects/provisioning-iam-ansible/galaxy/debops.php/meta/.galaxy_install_info'
```

**Comment by drybjed** [comment]
DebOps repository is a "multi-role repository" and using `ansible-galaxy` to install it will result in grief and gnashed teeth. Don't do it - use `mazer` instead, it will correctly install DebOps repository from Ansible Galaxy. Check the [installation instructions](https://docs.debops.org/en/master/user-guide/install.html#installation-from-ansible-galaxy) for more details.

**Comment by cmarquezrusso** [comment]
I just realised about that. I tried to reuse a 2.5 years old project but galaxy destroyed it. I cannot believe they changed it like that. :( Thanks anyways. Im closing this.
